apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    app: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back
          image: "532214462726.dkr.ecr.ap-northeast-2.amazonaws.com/backend:dev"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "{{ .Values.cpuLimits }}"
              memory: "{{ .Values.memoryLimits }}"
            requests:
              cpu: "{{ .Values.cpuRequests }}"
              memory: "{{ .Values.memoryRequests }}"
          lifecycle:
            preStop:
              exec:
                command: [
                  # Introduce a delay to the shutdown sequence to wait for the
                  # pod eviction event to propagate. Then, gracefully shutdown
                  "sh", "-c", "sleep 5",
                ]
