apiVersion: extensions/v1beta1
kind: front
metadata:
  name: "typo-checker-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app: front
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: front
              servicePort: 8000